apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-canary
  namespace: istioinaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata: 
      labels:
        app: sleep
        istio.io/rev: prod-canary
    spec:
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
---
